In [1]:
#!pip install pomegranate

In [2]:
#!pip install pymc3

In [3]:
#!pip install graphviz

In [4]:
#!pip install pygraphviz

In [5]:
#!pip install matplotlib

In [6]:
#!pip install openpyxl

In [7]:
#!pip install sklearn

In [1]:
#imports
import pandas as pd
import numpy as np
import arviz as az
import pymc3 as pm
import matplotlib.pyplot as plt
from pomegranate import *

WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [22]:
#read in data
pd.set_option('display.max_columns', None)

#name format is df survey#_wave# if resend, add (_2 at end)

df1_1 = pd.read_csv("survey1.1.csv", encoding='cp1252')
df1_1_2 = pd.read_csv("survey1.1.2.csv", encoding='cp1252')
df1_2 = pd.read_csv("survey1.2.csv", encoding ='cp1252')
#survey 1 wave 3
#survey1.3.csv
#df1_3 = pd.read_csv...
df2_1 = pd.read_csv("survey2.1.csv", encoding='cp1252')
df2_1_2 = pd.read_csv("survey2.1.2.csv", encoding='cp1252')
df2_2 = pd.read_csv("survey2.2.csv", encoding='cp1252')
df3_1 = pd.read_csv("survey3.1.csv", encoding='cp1252')
print(df2_2.shape)

(333, 70)


In [23]:
survey1 =pd.concat([df1_1, df1_1_2, df1_2]) #add df1_3
survey2 = pd.concat([df2_1, df2_1_2, df2_2])
survey3 = pd.concat([df3_1])
survey1['survey']=np.full(survey1.shape[0], 1)
survey2['survey']=np.full(survey2.shape[0], 2)
survey3['survey']=np.full(survey3.shape[0], 3)

main = pd.concat([survey1, survey2, survey3])
main

Date (Responses to recipient forms)  \
0                  2020/12/04 10:55:54   
1                  2020/12/04 10:56:29   
2                  2020/12/04 10:56:42   
3                  2020/12/04 10:57:02   
4                  2020/12/04 10:57:09   
..                                 ...   
7                  2021/02/04 12:18:38   
8                  2021/02/04 12:32:01   
9                  2021/02/04 12:37:44   
10                 2021/02/04 21:33:45   
11                 2021/02/05 18:11:58   

                                            Recipient  \
0           Evans Melanie (mryumyumsbakery@gmail.com)   
1           Miranda  Jennifer (jmiranda26@icloud.com)   
2               Zuniga Adam (zuniga.adam77@gmail.com)   
3              Black Thomas (andrearuszala@gmail.com)   
4   Jesseapontejr@Gmail.Com Jesse (jesseapontejr@g...   
..                                                ...   
7     Egersheim Melissa (mellieandxander@hotmail.com)   
8              Sikes Amber  (amber.sikes75@yahoo.com)   
9            Richard  Tracy  (dicktracyy@hotmail.com)   
10            Karsten Chris (chriskarsten1@gmail.com)   
11                    Waddell Robert (rjwbro@aol.com)   

    Origin (Responses to recipient forms)  \
0                                     NaN   
1                                     NaN   
2                                     NaN   
3                                     NaN   
4                                     NaN   
..                                    ...   
7                                     NaN   
8                                     NaN   
9                                     NaN   
10                                    NaN   
11                                    NaN   

    Score (Responses to recipient forms)  Primary key  \
0                                     15    397637986   
1                                     14    397628088   
2                                     15    397642487   
3                                     12    397637989   
4                                     15    397642488   
..                                   ...          ...   
7                                     15    405385254   
8                                     15    405396024   
9                                      7    405396027   
10                                     8    405396044   
11                                     9    405519321   

           Conditional: Portal Engagement Explanation  \
0                                                 NaN   
1                                                 NaN   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
..                                                ...   
7                                                 NaN   
8                                                 NaN   
9   I don’t have time now to become more engaged w...   
10                                                NaN   
11  I never received the Portal. Tell me how I can...   

    Caregiver for Active Duty Military (Constituent Type)  \
0                                                   0       
1                                                   0       
2                                                   0       
3                                                   0       
4                                                   0       
..                                                ...       
7                                                   0       
8                                                   0       
9                                                   0       
10                                                  0       
11                                                  0       

    Caregiver for Veteran (Constituent Type)  \
0                                          1   
1                                          1   
2                        

In [24]:
print(survey1.shape)
print(survey2.shape)
print(survey3.shape)

(702, 71)
(605, 71)
(12, 71)


In [25]:
toDrop = ['Date (Responses to recipient forms)', 'Age', 'Recipient', 'Origin (Responses to recipient forms)', 'Primary key', 'Conditional: Portal Engagement Explanation', 'Consent', 'Flow', 'Display and Format', 'Content', 'Sex', 'Race:', 'Time Providing Care', ]
main = main.drop(columns = toDrop)
#main.drop(list(main.filter(regex = 'Constituent Type')), axis = 1, inplace = True)
main.drop(list(main.filter(regex = 'Chronic Conditions')), axis = 1, inplace = True)
#main.drop(list(dropped_dfmain.filter(regex = 'Portal Video Use')), axis = 1, inplace = True)
#main.drop(list(dropped_dfmain.filter(regex = 'Connection Technology Use')), axis = 1, inplace = True)

In [35]:
copy = main.copy()
copy["Caregiver?"] = copy["Caregiver for Active Duty Military (Constituent Type)"] + copy["Caregiver for Veteran (Constituent Type)"] + copy["Other caregiver (Constituent Type)"]
copy = copy.sort_values(by = "Caregiver?")
copy = copy.reset_index(drop = True)
caregiverthing = copy["Caregiver?"]
counter = 0
while caregiverthing[counter] == 0:
    counter += 1
print (counter)
copy = copy.drop(columns = 'Score (Responses to recipient forms)')
copy.drop(list(copy.filter(regex = 'Constituent Type')), axis = 1, inplace = True)
copy = copy.drop(columns = "Caregiver?")
caregivers = copy.drop(copy.index[0:counter])
notCaregivers = copy.drop(copy.index[counter:len(copy.index)+1])
notCaregivers

481


Use of Video Conferencing Depression Motivation  Life Satisfaction  \
0               6 To 9 Months        Yes        Yes              Agree   
1                     1+ Year        Yes        Yes     Strongly Agree   
2               6 To 9 Months        Yes        Yes           Disagree   
3               6 To 9 Months         No         No  Strongly Disagree   
4               3 To 6 Months         No         No           Disagree   
..                        ...        ...        ...                ...   
476                 <3 Months        Yes        Yes            Neutral   
477             6 To 9 Months         No         No           Disagree   
478                 <3 Months        Yes        Yes            Neutral   
479            9 To 12 Months        Yes        Yes              Agree   
480                   1+ Year        Yes        Yes     Strongly Agree   

    Physical Exhaustion   Desire To Escape          Same Self  \
0                 Agree           Disagree            Neutral   
1        Strongly Agree     Strongly Agree     Strongly Agree   
2        Strongly Agree     Strongly Agree            Neutral   
3     Strongly Disagree  Strongly Disagree  Strongly Disagree   
4              Disagree           Disagree           Disagree   
..                  ...                ...                ...   
476      Strongly Agree           Disagree     Strongly Agree   
477               Agree            Neutral              Agree   
478               Agree              Agree              Agree   
479               Agree              Agree              Agree   
480               Agree            Neutral              Agree   

    Financial Decrease      Health Change Demands Strength   Competing Demand  \
0                Agree              Agree            Agree              Agree   
1              Neutral     Strongly Agree   Strongly Agree     Strongly Agree   
2    Strongly Disagree     Strongly Agree   Strongly Agree            Neutral   
3       Strongly Agree  Strongly Disagree         Disagree  Strongly Disagree   
4             Disagree           Disagree         Disagree            Neutral   
..                 ...                ...              ...                ...   
476     Strongly Agree            Neutral          Neutral     Strongly Agree   
477            Neutral           Disagree          Neutral            Neutral   
478            Neutral              Agree          Neutral            Neutral   
479              Agree     Strongly Agree   Strongly Agree            Neutral   
480     Strongly Agree     Strongly Agree            Agree              Agree   

    Concern About Future Relationship Impact  Portal Experience  \
0                Neutral             Neutral  Strongly Disagree   
1         Strongly Agree             Neutral     Strongly Agree   
2      Strongly Disagree      Strongly Agree     Strongly Agree   
3      Strongly Disagree   Strongly Disagree  Strongly Disagree   
4      Strongly Disagree             Neutral              Agree   
..                   ...                 ...                ...   
476              Neutral      Strongly Agree            Neutral   
477              Neutral             Neutral              Agree   
478             Disagree   Strongly Disagree              Agree   
479              Neutral      Strongly Agree     Strongly Agree   
480       Strongly Agree               Agree            Neutral   

     Portal Engagement Portal Engagement Reinforcement  \
0             Disagree               Strongly Disagree   
1       Strongly Agree                  Strongly Agree   
2       Strongly Agree                  Strongly Agree   
3    Strongly Disagree                         Neutral   
4              Neutral                           Agree   
..                 ...                             ...   
476              Agree                           Agree   
477              Agree                           Agree   
478              Agree            

In [36]:
encoding = {
    'Agree': 1,
    'StronglyAgree': 2,
    'Strongly Agree': 2,
    'StronglyDisagree': -2,
    'Strongly Disagree': -2,
    'Disagree': -1,
    'Neutral': 0,
    'Yes': 1,
    'No': -1,
    'Rarely':-1,
    'Never':-2,
    'Sometimes':1,
    'Always':2,
    '<6mo':-3,
    '6mo to 1year':-2,
    '1 to 2 years': -1,
    '2 to 3 years': 0,
    '3 to 4 years':1,
    '4-5 years': 2,
    '5+ years': 3, 
    '<3 Months': -2,
    '3 To 6 Months': -1,
    '6 To 9 Months': 0,
    '9 To 12 Months': 1,
    '1+ Year': 2,
    '0 - 17': -3,
    '18 - 24': -2,
    '25 - 34': -1,
    '35 - 44': 0,
    '45 - 54': 1,
    '55 - 64': 2,
    '65+': 3,
    'Male': 0,
    'Female': 1,
    'White': -2, 
    'Black or African American': -1,
    'Asian': 0,
    'American Indian or Alaska Native': 1,
    'Some other race': 2,
    'Native Hawaiian and Pacific Islander': 3  
}

def f(s):
    l = []
    for b in s:
        if (b in encoding):
            l.append(encoding[b])
        elif isinstance(b, str) and b.isnumeric():
            l.append(int(b))
        else:
            l.append(b)
    return pd.Series(l)


In [37]:
data1 = caregivers.apply(f, axis = 0)
data1 = data1.sample(frac=1).reset_index(drop=True)
data2 = notCaregivers.apply(f, axis = 0)
data2 = data2.sample(frac=1).reset_index(drop=True)
data2

Use of Video Conferencing  Depression  Motivation  Life Satisfaction  \
0                           -2          -1          -1                 -1   
1                           -2           1           1                 -1   
2                            0           1           1                 -1   
3                            2           1           1                  1   
4                            1           1           1                  0   
..                         ...         ...         ...                ...   
476                          1          -1          -1                 -2   
477                          2           1           1                  0   
478                          2          -1          -1                 -1   
479                          2          -1           1                  0   
480                          2           1           1                  0   

     Physical Exhaustion  Desire To Escape  Same Self  Financial Decrease  \
0                     -1                -1         -1                   0   
1                      1                 2          2                   2   
2                      0                -2         -2                  -2   
3                      1                 1          1                   1   
4                      1                -1          1                  -1   
..                   ...               ...        ...                 ...   
476                   -2                -1         -1                   0   
477                    2                 2          2                   0   
478                   -1                -1         -1                  -1   
479                    0                 1         -1                   1   
480                    1                 2          1                  -1   

     Health Change  Demands Strength  Competing Demand  Concern About Future  \
0                0                 1                 1                    -1   
1               -1                 0                 1                     0   
2               -2                 0                -1                    -1   
3                2                 2                 1                     2   
4                0                 0                 0                    -1   
..             ...               ...               ...                   ...   
476             -1                 2                -1                    -1   
477              1                 1                 1                     0   
478              1                 1                -1                    -1   
479             -1                 0                 0                     0   
480              0                 1                 1                     1   

     Relationship Impact  Portal Experience  Portal Engagement  \
0                     -1                  1                  1   
1                     -2                  2                  2   
2                     -1                  1                  1   
3                      2                  1                  1   
4                      0                  1                  1   
..                   ...                ...                ...   
476                   -1                  2                  2   
477                    1                  0                  0   
478                   -1                  1                  0   
479                    0                 -1                  1   
480                    2                  0                  0   

     Portal Engagement Reinforcement  Portal Wellbeing Influence  \
0                                  1                           1   
1                                  2                           1   
2                                  0                           1   
3                                  1                           0   
4                                  1                         

In [38]:
ls = []
for column in data2:
    ls.append(data2[column].unique())
ls

[array([-2,  0,  2,  1, -1], dtype=int64),
 array([-1,  1], dtype=int64),
 array([-1,  1], dtype=int64),
 array([-1,  1,  0,  2, -2], dtype=int64),
 array([-1,  1,  0,  2, -2], dtype=int64),
 array([-1,  2, -2,  1,  0], dtype=int64),
 array([-1,  2, -2,  1,  0], dtype=int64),
 array([ 0,  2, -2,  1, -1], dtype=int64),
 array([ 0, -1, -2,  2,  1], dtype=int64),
 array([ 1,  0,  2, -1, -2], dtype=int64),
 array([ 1, -1,  0,  2, -2], dtype=int64),
 array([-1,  0,  2,  1, -2], dtype=int64),
 array([-1, -2,  2,  0,  1], dtype=int64),
 array([ 1,  2,  0, -1, -2], dtype=int64),
 array([ 1,  2,  0, -2, -1], dtype=int64),
 array([ 1,  2,  0, -1, -2], dtype=int64),
 array([ 1,  0,  2, -1, -2], dtype=int64),
 array([ 1,  2, -1, -2], dtype=int64),
 array([-1,  1, -2,  2], dtype=int64),
 array([-1,  2,  1, -2], dtype=int64),
 array([-1,  1, -2,  2], dtype=int64),
 array([-1,  1, -2,  2], dtype=int64),
 array([-1,  1, -2,  2], dtype=int64),
 array([ 1,  2, -1, -2], dtype=int64),
 array([-1,  1, -2, 

In [39]:
import statsmodels.stats.weightstats as ssw

#results = []

#pd.set_option('display.max_rows', 500)
#for col in data1.columns: 
#    vals1 = data1[col].to_list()
#    vals2 = data2[col].to_list()
#    
#    # Null hypothesis: means are the same
#    # Alternative: the mean after is higher
#    
#    cm = ssw.CompareMeans(ssw.DescrStatsW(vals1), ssw.DescrStatsW(vals2))
#    res = cm.ztest_ind(alternative='smaller',usevar='unequal')
#    msg = "Cannot reject the null"
#    if (res[1] <= 0.05):
#        msg = "Alternative accepted: mean is larger"
#    elif (res[1] >= 0.95):
#        msg = "Alternative accepted: mean is smaller"
#    results.append([col, res[1], msg])
#
#res = pd.DataFrame(results, columns=['Item', 'P-Value', 'Verdict'])
#res

In [40]:
def analyze(before, after):
    results = []
    for col in before.columns: 
        vals1 = before[col].to_list()
        vals2 = after[col].to_list()

        # Null hypothesis: means are the same
        # Alternative: the mean after is higher

        cm = ssw.CompareMeans(ssw.DescrStatsW(vals1), ssw.DescrStatsW(vals2))
        res = cm.ztest_ind(alternative='smaller',usevar='unequal')
        msg = "Cannot reject the null"
        if (res[1] <= 0.05):
            msg = "Alternative accepted: mean is larger"
            results.append([col, res[1], msg])
        elif (res[1] >= 0.95):
            msg = "Alternative accepted: mean is smaller"
            results.append([col, 1-res[1], msg])
        else:
            results.append([col, res[1], msg])
    res = pd.DataFrame(results, columns=['Item', 'P-Value', 'Verdict'])
    return res

In [41]:
w1data1 = data1[data1['survey']==1]
w2data1 = data1[data1['survey']==2]
w1data2 = data2[data2['survey']==1]
w2data2 = data2[data2['survey']==2]

print(w1data1.shape)
print(w2data1.shape)
print(w1data2.shape)
print(w2data2.shape)

survey1totals = pd.concat([w1data1, w1data2])
survey2totals = pd.concat([w2data1, w2data2])

print(survey1totals.shape)
print(survey2totals.shape)
print(survey2totals.sum(axis = 0))
results = []

(429, 38)
(399, 38)
(273, 38)
(206, 38)
(702, 38)
(605, 38)
Use of Video Conferencing                     -22
Depression                                    103
Motivation                                     75
Life Satisfaction                             -59
Physical Exhaustion                           426
Desire To Escape                               82
Same Self                                     281
Financial Decrease                            161
Health Change                                 159
Demands Strength                              392
Competing Demand                              173
Concern About Future                           27
Relationship Impact                            96
Portal Experience                             556
Portal Engagement                             492
Portal Engagement Reinforcement               479
Portal Wellbeing Influence                    471
Unhappy Alone                                 299
No One To Talk To                       

In [42]:
res = analyze(w1data1, w1data2)
res

c:\users\14058\appdata\local\programs\python\python38\lib\site-packages\statsmodels\stats\weightstats.py:746: RuntimeWarning: invalid value encountered in double_scalars
  zstat = (value1 - value2 - diff) / std_diff


Item       P-Value  \
0                   Use of Video Conferencing  5.687674e-03   
1                                  Depression  6.386743e-06   
2                                  Motivation  1.003483e-07   
3                           Life Satisfaction  4.442009e-05   
4                         Physical Exhaustion  4.091408e-02   
5                            Desire To Escape  6.154437e-03   
6                                   Same Self  6.293072e-05   
7                          Financial Decrease  8.446745e-01   
8                               Health Change  9.456415e-01   
9                            Demands Strength  9.450235e-01   
10                           Competing Demand  7.963139e-01   
11                       Concern About Future  5.923766e-01   
12                        Relationship Impact  1.307222e-02   
13                          Portal Experience  4.320286e-01   
14                          Portal Engagement  7.932157e-01   
15            Portal Engagement Reinforcement  2.858995e-02   
16                 Portal Wellbeing Influence  1.979333e-02   
17                              Unhappy Alone  9.695219e-02   
18                          No One To Talk To  1.064156e-02   
19                  Cant Tolerate Being Alone  1.667668e-08   
20                      No One Understands Me  1.618050e-01   
21                        Waiting for Contact  2.760445e-01   
22                      Feel Completely Alone  5.255771e-02   
23                      Unable To Communicate  1.260168e-02   
24                               Need Company  4.762157e-01   
25                  Difficult to make friends  2.997448e-01   
26                              Feel Excluded  6.215813e-01   
27              Caregivers (Portal Video Use)  1.435468e-01   
28          Family members (Portal Video Use)  5.490432e-02   
29                 Friends (Portal Video Use)  2.950978e-02   
30                  Others (Portal Video Use)  1.055910e-01   
31  Not using Portal video (Portal Video Use)  6.831212e-03   
32       SMS/text (Connection Technology Use)  2.897533e-01   
33          Phone (Connection Technology Use)  3.570397e-03   
34   Video Portal (Connection Technology Use)  1.123368e-05   
35          Other (Connection Technology Use)  1.112684e-03   
36     Portal Chronic Disease Management Help  6.659891e-05   
37                                     survey           NaN   

                                  Verdict  
0   Alternative accepted: mean is smaller  
1    Alternative accepted: mean is larger  
2    Alternative accepted: mean is larger  
3   Alternative accepted: mean is smaller  
4    Alternative accepted: mean is larger  
5    Alternative accepted: mean is larger  
6    Alternative accepted: mean is larger  
7                  Cannot reject the null  
8                  Cannot reject the null  
9                  Cannot reject the null  
10                 Cannot reject the null  
11                 Cannot reject the null  
12  Alternative accepted: mean is smaller  
13                 Cannot reject the null  
14                 Cannot reject the null  
15   Alternative accepted: mean is larger  
16   Alternative accepted: mean is larger  
17                 Cannot reject the null  
18  Alternative accepted: mean is smaller  
19   Alternative accepted: mean is larger  
20                 Cannot reject the null  
21                 Cannot reject the null  
22                 Cannot reject the null  
23   Alternative accepted: mean is larger  
24                 Cannot reject the null  
25                 Cannot reject the null  
26                 Cannot reject the null  
27                 Cannot reject the null  
28                 Cannot reject the null  
29   Alternative accepted: mean is larger  
30                 Cannot reject the null  
31  Alternative accepted: mean is smaller  
32                 Cannot reject the null  
33   Alternative accepted: mean is larger  
34   Alternative accepted: mean is larger  

In [43]:
res = analyze(w2data1, w2data2)
res

c:\users\14058\appdata\local\programs\python\python38\lib\site-packages\statsmodels\stats\weightstats.py:746: RuntimeWarning: invalid value encountered in double_scalars
  zstat = (value1 - value2 - diff) / std_diff


Item   P-Value  \
0                   Use of Video Conferencing  0.698636   
1                                  Depression  0.000918   
2                                  Motivation  0.000007   
3                           Life Satisfaction  0.000001   
4                         Physical Exhaustion  0.442853   
5                            Desire To Escape  0.002093   
6                                   Same Self  0.000276   
7                          Financial Decrease  0.008332   
8                               Health Change  0.835952   
9                            Demands Strength  0.000235   
10                           Competing Demand  0.740534   
11                       Concern About Future  0.399503   
12                        Relationship Impact  0.005238   
13                          Portal Experience  0.699284   
14                          Portal Engagement  0.704978   
15            Portal Engagement Reinforcement  0.371854   
16                 Portal Wellbeing Influence  0.650696   
17                              Unhappy Alone  0.035941   
18                          No One To Talk To  0.276466   
19                  Cant Tolerate Being Alone  0.003063   
20                      No One Understands Me  0.019193   
21                        Waiting for Contact  0.101675   
22                      Feel Completely Alone  0.008729   
23                      Unable To Communicate  0.005977   
24                               Need Company  0.686336   
25                  Difficult to make friends  0.214556   
26                              Feel Excluded  0.099315   
27              Caregivers (Portal Video Use)  0.010123   
28          Family members (Portal Video Use)  0.044373   
29                 Friends (Portal Video Use)  0.915208   
30                  Others (Portal Video Use)  0.273401   
31  Not using Portal video (Portal Video Use)  0.126267   
32       SMS/text (Connection Technology Use)  0.145801   
33          Phone (Connection Technology Use)  0.004125   
34   Video Portal (Connection Technology Use)  0.165704   
35          Other (Connection Technology Use)  0.015970   
36     Portal Chronic Disease Management Help  0.501155   
37                                     survey       NaN   

                                  Verdict  
0                  Cannot reject the null  
1    Alternative accepted: mean is larger  
2    Alternative accepted: mean is larger  
3   Alternative accepted: mean is smaller  
4                  Cannot reject the null  
5    Alternative accepted: mean is larger  
6    Alternative accepted: mean is larger  
7   Alternative accepted: mean is smaller  
8                  Cannot reject the null  
9   Alternative accepted: mean is smaller  
10                 Cannot reject the null  
11                 Cannot reject the null  
12  Alternative accepted: mean is smaller  
13                 Cannot reject the null  
14                 Cannot reject the null  
15                 Cannot reject the null  
16                 Cannot reject the null  
17   Alternative accepted: mean is larger  
18                 Cannot reject the null  
19   Alternative accepted: mean is larger  
20   Alternative accepted: mean is larger  
21                 Cannot reject the null  
22   Alternative accepted: mean is larger  
23   Alternative accepted: mean is larger  
24                 Cannot reject the null  
25                 Cannot reject the null  
26                 Cannot reject the null  
27   Alternative accepted: mean is larger  
28  Alternative accepted: mean is smaller  
29                 Cannot reject the null  
30                 Cannot reject the null  
31                 Cannot reject the null  
32                 Cannot reject the null  
33   Alternative accepted: mean is larger  
34                 Cannot reject the null  
35  Alternative accepted: mean is smaller  
36                 Cannot reject the null  
37                 Cannot reject the null

In [44]:
res = analyze(w1data1, w2data1)
res

c:\users\14058\appdata\local\programs\python\python38\lib\site-packages\statsmodels\stats\weightstats.py:746: RuntimeWarning: divide by zero encountered in double_scalars
  zstat = (value1 - value2 - diff) / std_diff


Item       P-Value  \
0                   Use of Video Conferencing  5.916487e-10   
1                                  Depression  2.254080e-01   
2                                  Motivation  5.786121e-01   
3                           Life Satisfaction  3.895246e-03   
4                         Physical Exhaustion  8.649512e-03   
5                            Desire To Escape  1.156048e-01   
6                                   Same Self  1.054705e-01   
7                          Financial Decrease  1.910654e-02   
8                               Health Change  1.548388e-02   
9                            Demands Strength  5.037757e-05   
10                           Competing Demand  1.619914e-01   
11                       Concern About Future  4.538014e-02   
12                        Relationship Impact  7.995927e-02   
13                          Portal Experience  8.040910e-01   
14                          Portal Engagement  8.618642e-01   
15            Portal Engagement Reinforcement  6.065570e-01   
16                 Portal Wellbeing Influence  5.067540e-01   
17                              Unhappy Alone  4.777372e-02   
18                          No One To Talk To  1.691491e-01   
19                  Cant Tolerate Being Alone  8.365885e-02   
20                      No One Understands Me  6.024039e-01   
21                        Waiting for Contact  4.985605e-02   
22                      Feel Completely Alone  2.741572e-01   
23                      Unable To Communicate  2.795895e-02   
24                               Need Company  2.067561e-02   
25                  Difficult to make friends  3.845345e-01   
26                              Feel Excluded  4.196790e-02   
27              Caregivers (Portal Video Use)  8.285856e-01   
28          Family members (Portal Video Use)  8.244750e-06   
29                 Friends (Portal Video Use)  7.080626e-01   
30                  Others (Portal Video Use)  3.661369e-01   
31  Not using Portal video (Portal Video Use)  1.477942e-07   
32       SMS/text (Connection Technology Use)  1.098611e-03   
33          Phone (Connection Technology Use)  9.161255e-01   
34   Video Portal (Connection Technology Use)  2.103040e-03   
35          Other (Connection Technology Use)  3.242216e-01   
36     Portal Chronic Disease Management Help  5.445608e-01   
37                                     survey  0.000000e+00   

                                  Verdict  
0   Alternative accepted: mean is smaller  
1                  Cannot reject the null  
2                  Cannot reject the null  
3    Alternative accepted: mean is larger  
4    Alternative accepted: mean is larger  
5                  Cannot reject the null  
6                  Cannot reject the null  
7    Alternative accepted: mean is larger  
8    Alternative accepted: mean is larger  
9    Alternative accepted: mean is larger  
10                 Cannot reject the null  
11   Alternative accepted: mean is larger  
12                 Cannot reject the null  
13                 Cannot reject the null  
14                 Cannot reject the null  
15                 Cannot reject the null  
16                 Cannot reject the null  
17   Alternative accepted: mean is larger  
18                 Cannot reject the null  
19                 Cannot reject the null  
20                 Cannot reject the null  
21   Alternative accepted: mean is larger  
22                 Cannot reject the null  
23   Alternative accepted: mean is larger  
24   Alternative accepted: mean is larger  
25                 Cannot reject the null  
26   Alternative accepted: mean is larger  
27                 Cannot reject the null  
28  Alternative accepted: mean is smaller  
29                 Cannot reject the null  
30                 Cannot reject the null  
31   Alternative accepted: mean is larger  
32  Alternative accepted: mean is smaller  
33                 Cannot reject the null  
34  Alternative accepted: mean is smaller  

In [45]:
res = analyze(w1data2, w2data2)
res

c:\users\14058\appdata\local\programs\python\python38\lib\site-packages\statsmodels\stats\weightstats.py:746: RuntimeWarning: divide by zero encountered in double_scalars
  zstat = (value1 - value2 - diff) / std_diff


Item       P-Value  \
0                   Use of Video Conferencing  7.436174e-04   
1                                  Depression  5.709211e-01   
2                                  Motivation  6.799056e-01   
3                           Life Satisfaction  2.168560e-01   
4                         Physical Exhaustion  3.449518e-01   
5                            Desire To Escape  7.389975e-02   
6                                   Same Self  1.720985e-01   
7                          Financial Decrease  4.635020e-01   
8                               Health Change  2.478632e-02   
9                            Demands Strength  2.102073e-01   
10                           Competing Demand  2.074593e-01   
11                       Concern About Future  3.860035e-02   
12                        Relationship Impact  3.507488e-01   
13                          Portal Experience  8.835029e-01   
14                          Portal Engagement  7.156419e-01   
15            Portal Engagement Reinforcement  9.463845e-01   
16                 Portal Wellbeing Influence  1.522836e-02   
17                              Unhappy Alone  4.207136e-02   
18                          No One To Talk To  7.322826e-04   
19                  Cant Tolerate Being Alone  8.386932e-01   
20                      No One Understands Me  1.940013e-01   
21                        Waiting for Contact  2.676038e-02   
22                      Feel Completely Alone  1.056403e-01   
23                      Unable To Communicate  2.800526e-02   
24                               Need Company  1.456128e-01   
25                  Difficult to make friends  2.918719e-01   
26                              Feel Excluded  3.064299e-03   
27              Caregivers (Portal Video Use)  2.869728e-01   
28          Family members (Portal Video Use)  3.948945e-10   
29                 Friends (Portal Video Use)  4.981468e-04   
30                  Others (Portal Video Use)  5.936923e-01   
31  Not using Portal video (Portal Video Use)  2.008818e-11   
32       SMS/text (Connection Technology Use)  3.727962e-02   
33          Phone (Connection Technology Use)  8.022951e-01   
34   Video Portal (Connection Technology Use)  8.789369e-07   
35          Other (Connection Technology Use)  1.845361e-01   
36     Portal Chronic Disease Management Help  3.772886e-04   
37                                     survey  0.000000e+00   

                                  Verdict  
0   Alternative accepted: mean is smaller  
1                  Cannot reject the null  
2                  Cannot reject the null  
3                  Cannot reject the null  
4                  Cannot reject the null  
5                  Cannot reject the null  
6                  Cannot reject the null  
7                  Cannot reject the null  
8    Alternative accepted: mean is larger  
9                  Cannot reject the null  
10                 Cannot reject the null  
11   Alternative accepted: mean is larger  
12                 Cannot reject the null  
13                 Cannot reject the null  
14                 Cannot reject the null  
15                 Cannot reject the null  
16  Alternative accepted: mean is smaller  
17   Alternative accepted: mean is larger  
18   Alternative accepted: mean is larger  
19                 Cannot reject the null  
20                 Cannot reject the null  
21   Alternative accepted: mean is larger  
22                 Cannot reject the null  
23   Alternative accepted: mean is larger  
24                 Cannot reject the null  
25                 Cannot reject the null  
26   Alternative accepted: mean is larger  
27                 Cannot reject the null  
28  Alternative accepted: mean is smaller  
29  Alternative accepted: mean is smaller  
30                 Cannot reject the null  
31   Alternative accepted: mean is larger  
32  Alternative accepted: mean is smaller  
33                 Cannot reject the null  
34  Alternative accepted: mean is smaller  

In [ ]:
pd.set_option('display.max_rows', 100)
data.sort_values(by=['survey'])

In [ ]:
#toDrop2 = ['Depression', 'Motivation', 'Physical Exhaustion', 'Desire To Escape', 'Same Self', 'Financial Decrease', 'Health Change', 'Demands Strength', 'Competing Demand', 'Concern About Future', 'Relationship Impact', 'Unhappy Alone', 'No One To Talk To', 'Cant Tolerate Being Alone', 'No One Understands Me', 'Waiting for Contact', 'Feel Completely Alone', 'Unable To Communicate', 'Need Company', 'Difficult to make friends', 'Feel Excluded']
toDrop3 = ['Score (Responses to recipient forms)']
data1 = data.drop(columns = toDrop2)
data1 = data.drop(columns = toDrop3)
data1.shape

In [ ]:
test1 = data[data['survey']==1]['Use of Video Conferencing']
test2 = data[data['survey']==2]['Use of Video Conferencing']
print(test1.sum()/test1.shape[0])
print(test2.sum()/test2.shape[0])

In [ ]:
train_size = int(data1.shape[0]*0.8)
test_size = int(data1.shape[0]*0.2)

In [ ]:
#creates Bayesian model using data

dtrain = data1[:train_size]
dtest = data1[:-test_size]

In [ ]:
model = BayesianNetwork.from_samples(dtrain)

In [ ]:
blanked = dtest.copy()
blanked['Score (Responses to recipient forms)'] = np.full(blanked.shape[0], None)
prediction = model.predict(blanked.values.tolist())
mean = dtest["Score (Responses to recipient forms)"].mean()
rss = 0
tss = 0
correct = 0
for i in range (0, dtest.shape[0]):
    yBar = prediction[i][0]
    
    yActual = dtest['Score (Responses to recipient forms)'][i]
    
    if (yBar == yActual):
        correct+=1
    
    rss += (yActual-yBar)**2
    tss += (yActual-mean)**2

percent = float(correct) / dtest.shape[0]
r2 = 1-float(rss)/tss
print("Accuracy: " + (str)(percent))
print("r^2: " + (str)(r2))


from sklearn.metrics import precision_score, recall_score, accuracy_score, r2_score

labels = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
y_true = dtest['Score (Responses to recipient forms)']
y_pred = [row[0] for row in prediction]

precision = precision_score(y_true, y_pred, labels=labels, average='micro')
recall = recall_score(y_true, y_pred, labels=labels, average='micro')
accuracy = accuracy_score(y_true, y_pred)
# Need to make y_true shape (samples, classes)

#y_true = y_true.values.reshape((y_true.shape[0],len(labels)))
#y_pred = y_pred.reshape((y_pred.shape[0],len(labels)))

r_squared = r2_score(y_true, y_pred)
#auc = roc_auc_score(y_true, y_pred)

print('Accuracy: %.3f' % accuracy)
print('R^2: %.3f' % r_squared)
print('Precision: %.3f' % precision)
print('Recall: %.3f' % recall)
#print('ROC AUC: %.3f' % auc)

In [ ]:
blanked = dtest.copy()
blanked['Life Satisfaction'] = np.full(blanked.shape[0], None)
prediction = model.predict(blanked.values.tolist())
mean = dtest["Life Satisfaction"].mean()
rss = 0
tss = 0
correct = 0
for i in range (0, dtest.shape[0]):
    yBar = prediction[i][0]
    
    yActual = dtest['Life Satisfaction'][i]
    print(yBar)
    if (yBar == yActual):
        correct+=1
    
    rss += (yActual-yBar)**2
    tss += (yActual-mean)**2

percent = float(correct) / dtest.shape[0]
r2 = 1-float(rss)/tss
print("Accuracy: " + (str)(percent))
print("r^2: " + (str)(r2))


from sklearn.metrics import precision_score, recall_score, accuracy_score, r2_score

labels = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
y_true = dtest['Life Satisfaction']
y_pred = [row[0] for row in prediction]

precision = precision_score(y_true, y_pred, labels=labels, average='micro')
recall = recall_score(y_true, y_pred, labels=labels, average='micro')
accuracy = accuracy_score(y_true, y_pred)
# Need to make y_true shape (samples, classes)

#y_true = y_true.values.reshape((y_true.shape[0],len(labels)))
#y_pred = y_pred.reshape((y_pred.shape[0],len(labels)))

r_squared = r2_score(y_true, y_pred)
#auc = roc_auc_score(y_true, y_pred)

print('Accuracy: %.3f' % accuracy)
print('R^2: %.3f' % r_squared)
print('Precision: %.3f' % precision)
print('Recall: %.3f' % recall)
#print('ROC AUC: %.3f' % auc)

In [ ]:
from pymc3.glm import GLM

with pm.Model() as model_glm:
    GLM.from_formula("Life_Satisfaction ~ Caregiver_for_Veteran + Other_caregiver + Veteran + Other + Hypertension_high_blood_pressure_Chronic_Conditions + Hyperlipidemia_high_blood_cholesterol_or_triglyceride_levels_Chronic_Conditions + Allergies + sinusitis_and_other_upper_respiratory_conditions_Chronic_Conditions + Arthritis_Chronic_Conditions + Mood_Disorder_depression_and_bipolar_disorder_Chronic_Conditions + Diabetes_Type1_and_Type_2_Chronic_Conditions + Anxiety_Disorder_Chronic_Conditions + Asthma_Chronic_Conditions + Coronary_artery_disease_includes_myocardial_infarction_heart_attack_Chronic_Conditions + Thyroid_disorder_Chronic_Conditions + Chronic_obstructive_lung_disease_and_bronchiectasis_Chronic_Condition + Traumatic_Brain_Injury__TBI_Chronic_Conditions + Post_Traumatic_Stress_Disorder_PTSD_Chronic_Conditions + None_of_the_above__Chronic_Conditions + Caregivers_Portal_Video_Use + Family_members__Portal_Video_Us + Friends_Portal_Video_Use + Others_Portal_Video_Use + Not_using_Portal_video_Portal_Video_Use + Portal_Chronic_Disease_Management_Help + SMS_text_Connection_Technology_Use + Phone_Connection_Technology_Use + Video_Portal_Connection_Technology_Use + Other_Connection_Technology_Use + before", dtrain)
    trace = pm.sample()

In [ ]:
with model_glm:
    axes_arr = az.plot_trace(trace)
plt.draw()

In [ ]:
blanked = dtest.copy(dtest)
blanked['Life_Satisfaction'] = np.full(blanked.shape[0])
prediction = model.predict(blanked)
mean = dtest["weight"].mean()
rss = 0
tss = 0
correct = 0
for i in range (0, dtest.shape[0]):
    yBar = prediction['Life_Satisfaction'][i]
    yActual = dtest['Life_Satisfaction'][i]
    if (yBar == yActual):
        correct+=1
    rss += (yActual-yBar)**2
    tss += (yActual-mean)**2
percent = (float)correct/200
r2 = 1-(float)rss/tss
print("Accuracy: " + (str)(percent))
print("r^2: " + (str)(r2))

from sklearn.metrics import precision_score, recall_score, accuracy_score, r2_score

labels = [-2, -1, 0, 1, 2]
y_true = dtest['Life_Satisfaction']
y_pred = prediction['Life_Satisfaction']

precision = precision_score(y_true, y_pred, labels=labels, average='micro')
recall = recall_score(y_true, y_pred, labels=labels, average='micro')
accuracy = accuracy_score(y_true, y_pred)
# Need to make y_true shape (samples, classes)

y_true = y_true.reshape((y_true.shape[0],len(labels)))
y_pred = y_pred.reshape((y_pred.shape[0],len(labels)))

r_squared = r2_score(y_true, y_pred)
auc = roc_auc_score(y_true, y_pred)

print('Accuracy: %.3f' % accuracy)
print('R^2: %.3f' % r_squared)
print('Precision: %.3f' % precision)
print('Recall: %.3f' % recall)
print('ROC AUC: %.3f' % auc)